export const TemplateType = {
  1: {
    templatename: 'MCQ (Single response) Text and Audio',
    oldtemplatename: 'MCQ (Single response) Text and Audio',
    templateinstructions: 'MCQ (Single response) Text and Audio',
    templateid: 1,
    oldtemplateid: 1,
  },
  2: {
    templatename: 'MCQ (Single response) Picture',
    oldtemplatename: 'MCQ (Single response) Picture',
    templateinstructions: 'MCQ (Single response) Picture',
    templateid: 2,
    oldtemplateid: 2,
  },
  3: {
    templatename: 'MCQ (Multi Correct) Text and Audio',
    oldtemplatename: 'MCQ (Multi Correct) Text and Audio',
    templateinstructions: 'MCQ (Multi Correct) Text and Audio',
    templateid: 3,
    oldtemplateid: 3,
  },
  4: {
    templatename: 'MCQ (Multi Correct) Picture',
    oldtemplatename: 'MCQ (Multi Correct) Picture',
    templateinstructions: 'MCQ (Multi Correct) Picture',
    templateid: 4,
    oldtemplateid: 4,
  },
  5: {
    templatename: 'Correct Ordering (Text sequence)',
    oldtemplatename: 'Correct Ordering (Text sequence)',
    templateinstructions: 'Correct Ordering (Text sequence)',
    templateid: 5,
    oldtemplateid: 5,
  },
  6: {
    templatename: 'Correct Ordering (Pic sequence)',
    oldtemplatename: 'Correct Ordering (Pic sequence)',
    templateinstructions: 'Correct Ordering (Pic sequence)',
    templateid: 6,
    oldtemplateid: 6,
  },
  7: {
    templatename: 'Associate',
    oldtemplatename: 'Associate',
    templateinstructions: 'Associate',
    templateid: 7,
    oldtemplateid: 7,
  },
  8: {
    templatename: 'Fill in the blanks',
    oldtemplatename: 'Fill in the blanks',
    templateinstructions: 'Fill in the blanks',
    templateid: 8,
    oldtemplateid: 8,
  },
  9: {
    templatename: 'Q-Text & Audio-A-Audio',
    oldtemplatename: 'Q-Text & Audio-A-Audio',
    templateinstructions: 'Q-Text & Audio-A-Audio',
    templateid: 9,
    oldtemplateid: 9,
  },
  10: {
    templatename: 'Q-Text-A-Audio',
    oldtemplatename: 'Q-Text-A-Audio',
    templateinstructions: 'Q-Text-A-Audio',
    templateid: 10,
    oldtemplateid: 10,
  },
  11: {
    templatename: 'Q-Audio-A-Text',
    oldtemplatename: 'Q-Audio-A-Text',
    templateinstructions: 'Q-Audio-A-Text',
    templateid: 11,
    oldtemplateid: 11,
  },
  12: {
    templatename: 'Q-Text-A-Image',
    oldtemplatename: 'Q-Text-A-Image',
    templateinstructions: 'Q-Text-A-Image',
    templateid: 12,
    oldtemplateid: 12,
  },
  13: {
    templatename: 'Q-Audio-A-Audio',
    oldtemplatename: 'Q-Audio-A-Audio',
    templateinstructions: 'Q-Audio-A-Audio',
    templateid: 13,
    oldtemplateid: 13,
  },
  14: {
    templatename: 'Q-Text-A-Text',
    oldtemplatename: 'Q-Text-A-Text',
    templateinstructions: 'Q-Text-A-Text',
    templateid: 14,
    oldtemplateid: 14,
  },
  15: {
    templatename: 'Q-Image-A-Text',
    oldtemplatename: 'Q-Image-A-Text',
    templateinstructions: 'Q-Image-A-Text',
    templateid: 15,
    oldtemplateid: 15,
  },
  16: {
    templatename: 'Q-Image-A-Image',
    oldtemplatename: 'Q-Image-A-Image',
    templateinstructions: 'Q-Image-A-Image',
    templateid: 16,
    oldtemplateid: 16,
  },
  17: {
    templatename: 'Q-Audio-A-Image',
    oldtemplatename: 'Q-Audio-A-Image',
    templateinstructions: 'Q-Audio-A-Image',
    templateid: 17,
    oldtemplateid: 17,
  },
};
